### ISSUE TITLE
Seeed voicecard not properly initialized

### ISSUE THREAD

**Issue by norbusan** [respeaker/seeed-voicecard#166]
Hi all,
it seems on latest raspbian I cannot install the seeed voicecard. Installation runs fine, but there are a few issues:
- the kernel `config.txt` gets entries
```
dtoverlay=i2s-mmap
dtparam=i2s=on
dtoverlay=seeed-2mic-voicecard
```
but it seems that `i2s-mmap` is gone:
```
$ sudo dtoverlay i2s-mmap
DTOVERLAY[error]: Failed to open '/boot/overlays/i2s-mmap.dtbo'
* Failed to read '/boot/overlays/i2s-mmap.dtbo'
$
```
Furthermore, then the seeed-2mic overlay cannot be loaded:
```
$ sudo dtoverlay seeed-2mic-voicecard
* Failed to apply overlay '4_seeed-2mic-voicecard' (kernel)
$
```
This is with kernel
```
Linux raspberrypi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
```
and the kernel package is raspberrypi-kernel 1.20190517-1. I checked the changes in the kernel packages and the associated firmware package, but couldn't spot anything strange.

- I guess as a consequence, loading the alsa state fails:
```
$ sudo alsactl restore
Found hardware: "bcm2835_alsa" "Broadcom Mixer" "" "" ""
Hardware is initialized using a generic method
alsactl: set_control:1325: failed to obtain info for control #6 (No such file or directory)
```

Could you please look into this and advice what to do?

**Comment by norbusan** [comment]
I attach the log file created in `/var/log/seeed-voicecard.log`
[seeed-voicecard.log](https://github.com/respeaker/seeed-voicecard/files/3255270/seeed-voicecard.log)

**Comment by Pillar1989** [comment]
dtoverlay is no longer functional on the latest kernel, and if you want to add dtbo files dynamically, you can only read and write config.txt files

**Comment by norbusan** [comment]
Oh??? Is this a "bug" or a "feature" of the latest kernel? I thought dtoverlay is necessary to activate various functionalities for additional hats. I would be surprised if removing that functionality was on purpose... Do you @Pillar1989 have more information about this?

**Comment by norbusan** [comment]
Ah, maybe you meant that loading is only possible via config.txt. But even there it does not work ...

**Comment by Pillar1989** [comment]
It works. Our default install.sh script is used in this way.

**Comment by norbusan** [comment]
Hmmm, I *am* running your install.sh script right from the git repository checkout ... the above was after running the script and rebooting.

**Comment by wdavalil** [comment]
im haven a similar problem too

**Comment by martinjuhasz** [comment]
just freshly installed latest raspbian and `apt-get upgrade`'d my device. cloned the repo and installed it. went fine but afterwards i get the same problems as above. also the device doesn't show up on alsa.
```
pi@snips-01:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@snips-01:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
pi@snips-01:~ $ sudo dtoverlay i2s-mmap
DTOVERLAY[error]: Failed to open '/boot/overlays/i2s-mmap.dtbo'
* Failed to read '/boot/overlays/i2s-mmap.dtbo'
pi@snips-01:~ $
```

**Comment by martinjuhasz** [comment]
Strange, i just used an older `2018-11-13-raspbian-stretch` image of raspbian, didn't upgrade it and went straight to install. after reboot i still don't see the playback or recording device listed.

any idea what is happening?

```
git clone https://github.com/respeaker/seeed-voicecard.git
cd seeed-voicecard
sudo ./install.sh
sudo reboot
```

```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
```

**Comment by turmary** [comment]
@martinjuhasz  Please show me the log of below commands.
dmesg
cat /var/log/seeed-voicecard.log

**Comment by martinjuhasz** [comment]
OK sure. Which commands should i have run before so the log makes sense?
What i now did:
```
aplay -l
arecord -l
sudo dtoverlay i2s-mmap
sudo dtoverlay seeed-2mic-voicecard
```

<details>
    <summary> dmesg</summary>

```
    [    0.000000] Booting Linux on physical CPU 0x0
    [    0.000000] Linux version 4.19.42+ (dom@dom-XPS-13-9370) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1219 Tue May 14 21:16:38 BST 2019
    [    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
    [    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
    [    0.000000] OF: fdt: Machine model: Raspberry Pi Zero W Rev 1.1
    [    0.000000] Memory policy: Data cache writeback
    [    0.000000] cma: Reserved 8 MiB at 0x1b400000
    [    0.000000] On node 0 totalpages: 114688
    [    0.000000]   Normal zone: 1008 pages used for memmap
    [    0.000000]   Normal zone: 0 pages reserved
    [    0.000000]   Normal zone: 114688 pages, LIFO batch:31
    [    0.000000] random: get_random_bytes called from start_kernel+0x8c/0x49c with crng_init=0
    [    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
    [    0.000000] pcpu-alloc: [0] 0
    [    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 113680
    [    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 smsc95xx.macaddr=B8:27:EB:75:B2:4A vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=d532b144-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
    [    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
    [    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
    [    0.000000] Memory: 434484K/458752K available (6932K kernel code, 633K rwdata, 2068K rodata, 456K init, 797K bss, 16076K reserved, 8192K cma-reserved)
    [    0.000000] Virtual kernel memory layout:
                    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                    fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                    vmalloc : 0xdc800000 - 0xff800000   ( 560 MB)
                    lowmem  : 0xc0000000 - 0xdc000000   ( 448 MB)
                    modules : 0xbf000000 - 0xc0000000   (  16 MB)
                        .text : 0x(ptrval) - 0x(ptrval)   (6934 kB)
                        .init : 0x(ptrval) - 0x(ptrval)   ( 456 kB)
                        .data : 0x(ptrval) - 0x(ptrval)   ( 634 kB)
                        .bss : 0x(ptrval) - 0x(ptrval)   ( 798 kB)
    [    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
    [    0.000000] ftrace: allocating 25044 entries in 74 pages
    [    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
    [    0.000030] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 2147483647500ns
    [    0.000087] clocksource: timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275 ns
    [    0.000195] bcm2835: system timer (irq = 27)
    [    0.000793] Console: colour dummy device 80x30
    [    0.001431] console [tty1] enabled
    [    0.001513] Calibrating delay loop... 697.95 BogoMIPS (lpj=3489792)
    [    0.060374] pid_max: default: 32768 minimum: 301
    [    0.060970] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
    [    0.061030] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
    [    0.062498] CPU: Testing write buffer coherency: ok
    [    0.063887] Setting up static identity map for 0x8200 - 0x8238
    [    0.065347] devtmpfs: initialized
    [    0.076318] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
    [    0.076784] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
    [    0.076859] futex hash table entries: 256 (order: -1, 3072 bytes)
    [    0.078251] pinctrl core: initialized pinctrl subsystem
    [    0.079884] NET: Registered protocol family 16
    [    0.083209] DMA: preallocated 1024 KiB pool for atomic coherent allocations
    [    0.090376] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
    [    0.090553] hw-breakpoint: maximum watchpoint size is 4 bytes.
    [    0.090791] Serial: AMBA PL011 UART driver
    [    0.094386] bcm2835-mbox 2000b880.mailbox: mailbox enabled
    [    0.138062] bcm2835-dma 20007000.dma: DMA legacy API manager at (ptrval), dmachans=0x1
    [    0.140631] SCSI subsystem initialized
    [    0.141155] usbcore: registered new interface driver usbfs
    [    0.141309] usbcore: registered new interface driver hub
    [    0.141524] usbcore: registered new device driver usb
    [    0.160979] raspberrypi-firmware soc:firmware: Attached to firmware from 2019-03-27 15:45, variant start
    [    0.171011] raspberrypi-firmware soc:firmware: Firmware hash is 2e98b31d18547962e564bdf88e57b3df7085c29b
    [    0.183400] clocksource: Switched to clocksource timer
    [    0.284755] VFS: Disk quotas dquot_6.6.0
    [    0.284942] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
    [    0.285308] FS-Cache: Loaded
    [    0.285684] CacheFiles: Loaded
    [    0.304614] NET: Registered protocol family 2
    [    0.306010] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes)
    [    0.306137] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
    [    0.306248] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
    [    0.306366] TCP: Hash tables configured (established 4096 bind 4096)
    [    0.306559] UDP hash table entries: 256 (order: 0, 4096 bytes)
    [    0.306624] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
    [    0.307072] NET: Registered protocol family 1
    [    0.308217] RPC: Registered named UNIX socket transport module.
    [    0.308282] RPC: Registered udp transport module.
    [    0.308310] RPC: Registered tcp transport module.
    [    0.308335] RPC: Registered tcp NFSv4.1 backchannel transport module.
    [    0.310495] hw perfevents: no irqs for PMU, sampling events not supported
    [    0.310621] hw perfevents: enabled with armv6_1176 PMU driver, 3 counters available
    [    0.314775] Initialise system trusted keyrings
    [    0.315243] workingset: timestamp_bits=14 max_order=17 bucket_order=3
    [    0.330074] FS-Cache: Netfs 'nfs' registered for caching
    [    0.331451] NFS: Registering the id_resolver key type
    [    0.331551] Key type id_resolver registered
    [    0.331584] Key type id_legacy registered
    [    0.331636] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
    [    0.337480] Key type asymmetric registered
    [    0.337551] Asymmetric key parser 'x509' registered
    [    0.337689] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 250)
    [    0.338206] io scheduler noop registered
    [    0.338264] io scheduler deadline registered (default)
    [    0.338885] io scheduler cfq registered
    [    0.338935] io scheduler mq-deadline registered (default)
    [    0.338969] io scheduler kyber registered
    [    0.342207] BCM2708FB: allocated DMA memory 0x5b500000
    [    0.342323] BCM2708FB: allocated DMA channel 0
    [    0.350477] Console: switching to colour frame buffer device 82x26
    [    0.361480] bcm2835-rng 20104000.rng: hwrng registered
    [    0.364664] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
    [    0.371059] vc-sm: Videocore shared memory driver
    [    0.374568] gpiomem-bcm2835 20200000.gpiomem: Initialised: Registers at 0x20200000
    [    0.400792] brd: module loaded
    [    0.417116] loop: module loaded
    [    0.419896] Loading iSCSI transport class v2.0-870.
    [    0.423707] usbcore: registered new interface driver smsc95xx
    [    0.426515] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
    [    0.457232] dwc_otg 20980000.usb: base=(ptrval)
    [    0.660311] Core Release: 2.80a
    [    0.662921] Setting default values for core params
    [    0.665625] Finished setting default values for core params
    [    0.868732] Using Buffer DMA mode
    [    0.871425] Periodic Transfer Interrupt Enhancement - disabled
    [    0.874185] Multiprocessor Interrupt Enhancement - disabled
    [    0.876956] OTG VER PARAM: 0, OTG VER FLAG: 0
    [    0.879802] Dedicated Tx FIFOs mode
    [    0.883563] WARN::dwc_otg_hcd_init:1045: FIQ DMA bounce buffers: virt = db514000 dma = 0x5b514000 len=9024
    [    0.889152] FIQ FSM acceleration enabled for :
                Non-periodic Split Transactions
                Periodic Split Transactions
                High-Speed Isochronous Endpoints
                Interrupt/Control Split Transaction hack enabled
    [    0.901956] dwc_otg: Microframe scheduler enabled
    [    0.902210] WARN::hcd_init_fiq:457: FIQ on core 0
    [    0.904849] WARN::hcd_init_fiq:458: FIQ ASM at c04f48a0 length 36
    [    0.907416] WARN::hcd_init_fiq:484: MPHI regs_base at f0006000
    [    0.910163] dwc_otg 20980000.usb: DWC OTG Controller
    [    0.912871] dwc_otg 20980000.usb: new USB bus registered, assigned bus number 1
    [    0.915650] dwc_otg 20980000.usb: irq 56, io mem 0x00000000
    [    0.918305] Init: Port Power? op_state=1
    [    0.920854] Init: Power Port (0)
    [    0.923775] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.19
    [    0.928924] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
    [    0.931664] usb usb1: Product: DWC OTG Controller
    [    0.934424] usb usb1: Manufacturer: Linux 4.19.42+ dwc_otg_hcd
    [    0.937179] usb usb1: SerialNumber: 20980000.usb
    [    0.940910] hub 1-0:1.0: USB hub found
    [    0.943731] hub 1-0:1.0: 1 port detected
    [    0.947324] dwc_otg: FIQ enabled
    [    0.947336] dwc_otg: NAK holdoff enabled
    [    0.947344] dwc_otg: FIQ split-transaction FSM enabled
    [    0.947364] Module dwc_common_port init
    [    0.947928] usbcore: registered new interface driver usb-storage
    [    0.951082] mousedev: PS/2 mouse device common for all mice
    [    0.955304] bcm2835-wdt 20100000.watchdog: Broadcom BCM2835 watchdog timer
    [    0.958692] bcm2835-cpufreq: min=700000 max=1000000
    [    0.962227] sdhci: Secure Digital Host Controller Interface driver
    [    0.965131] sdhci: Copyright(c) Pierre Ossman
    [    0.968554] mmc-bcm2835 20300000.mmc: could not get clk, deferring probe
    [    0.972222] sdhost-bcm2835 20202000.mmc: could not get clk, deferring probe
    [    0.975635] sdhci-pltfm: SDHCI platform and OF driver helper
    [    0.979238] ledtrig-cpu: registered to indicate activity on CPUs
    [    0.982365] hidraw: raw HID events driver (C) Jiri Kosina
    [    0.985706] usbcore: registered new interface driver usbhid
    [    0.988698] usbhid: USB HID core driver
    [    0.992655] vchiq: vchiq_init_state: slot_zero = (ptrval), is_master = 0
    [    0.997974] [vc_sm_connected_init]: start
    [    1.008463] [vc_sm_connected_init]: end - returning 0
    [    1.013139] Initializing XFRM netlink socket
    [    1.016181] NET: Registered protocol family 17
    [    1.019113] Key type dns_resolver registered
    [    1.023818] registered taskstats version 1
    [    1.026696] Loading compiled-in X.509 certificates
    [    1.039706] uart-pl011 20201000.serial: cts_event_workaround enabled
    [    1.042757] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81, base_baud = 0) is a PL011 rev2
    [    1.051332] mmc-bcm2835 20300000.mmc: mmc_debug:0 mmc_debug2:0
    [    1.054416] mmc-bcm2835 20300000.mmc: DMA channel allocated
    [    1.086007] sdhost: log_buf @ (ptrval) (5b513000)
    [    1.125834] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
    [    1.130486] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
    [    1.134908] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
    [    1.140526] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
    [    1.143065] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
    [    1.147211] of_cfs_init
    [    1.149790] of_cfs_init: OK
    [    1.153124] Waiting for root device PARTUUID=d532b144-02...
    [    1.178626] random: fast init done
    [    1.245429] mmc0: host does not support reading read-only switch, assuming write-enable
    [    1.253975] mmc0: new high speed SDHC card at address aaaa
    [    1.258760] mmcblk0: mmc0:aaaa SB32G 29.7 GiB
    [    1.267447]  mmcblk0: p1 p2
    [    1.293731] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
    [    1.298934] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
    [    1.312260] mmc1: new high speed SDIO card at address 0001
    [    1.321941] devtmpfs: mounted
    [    1.329208] Freeing unused kernel memory: 456K
    [    1.331850] This architecture does not have kernel memory protection.
    [    1.334574] Run /sbin/init as init process
    [    1.878154] systemd[1]: System time before build time, advancing clock.
    [    2.041034] NET: Registered protocol family 10
    [    2.046322] Segment Routing with IPv6
    [    2.092211] random: systemd: uninitialized urandom read (16 bytes read)
    [    2.106037] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
    [    2.116855] systemd[1]: Detected architecture arm.
    [    2.137274] systemd[1]: Set hostname to <raspberrypi>.
    [    2.214656] random: systemd: uninitialized urandom read (16 bytes read)
    [    2.461503] random: systemd-gpt-aut: uninitialized urandom read (16 bytes read)
    [    3.254267] systemd[1]: Listening on udev Kernel Socket.
    [    3.264303] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
    [    3.275951] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
    [    3.287828] systemd[1]: Listening on Syslog Socket.
    [    3.296241] systemd[1]: Listening on fsck to fsckd communication Socket.
    [    3.305930] systemd[1]: Created slice User and Session Slice.
    [    3.314517] systemd[1]: Listening on Journal Socket.
    [    4.365323] snd_soc_seeed_voicecard: loading out-of-tree module taints kernel.
    [    6.363565] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
    [    6.966520] systemd-journald[73]: Received request to flush runtime journal from PID 1
    [    9.188356] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
    [    9.190578] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
    [    9.190603] [vc_sm_connected_init]: start
    [    9.213728] [vc_sm_connected_init]: installed successfully
    [    9.215649] media: Linux media interface: v0.10
    [    9.377191] videodev: Linux video capture interface: v2.00
    [    9.493753] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
    [    9.536315] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
    [    9.609378] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
    [    9.766434] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
    [    9.834569] bcm2835_audio soc:audio: card created with 8 channels
    [   10.254642] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
    [   10.254663] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
    [   10.267322] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
    [   10.267344] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
    [   10.297422] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
    [   10.297444] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
    [   10.968723] cfg80211: Loading compiled-in X.509 certificates for regulatory database
    [   11.477859] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
    [   12.233819] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
    [   12.273843] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
    [   12.274290] usbcore: registered new interface driver brcmfmac
    [   12.686104] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
    [   12.686308] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
    [   12.687398] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
    [   15.100857] random: crng init done
    [   15.100882] random: 7 urandom warning(s) missed due to ratelimiting
    [   15.656053] uart-pl011 20201000.serial: no DMA platform data
    [   18.368185] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
    [   20.191080] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
    [   20.191100] brcmfmac: power management disabled
    [   20.321701] Bluetooth: Core ver 2.22
    [   20.321874] NET: Registered protocol family 31
    [   20.321882] Bluetooth: HCI device and connection manager initialized
    [   20.321907] Bluetooth: HCI socket layer initialized
    [   20.321923] Bluetooth: L2CAP socket layer initialized
    [   20.321970] Bluetooth: SCO socket layer initialized
    [   20.348619] Bluetooth: HCI UART driver ver 2.3
    [   20.348635] Bluetooth: HCI UART protocol H4 registered
    [   20.352371] Bluetooth: HCI UART protocol Three-wire (H5) registered
    [   20.352667] Bluetooth: HCI UART protocol Broadcom registered
    [   20.444620] systemd[1]: apt-daily.timer: Adding 10h 19min 31.703709s random time.
    [   20.475316] systemd[1]: apt-daily-upgrade.timer: Adding 8min 18.787731s random time.
    [   21.486570] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
    [   21.486585] Bluetooth: BNEP filters: protocol multicast
    [   21.486610] Bluetooth: BNEP socket layer initialized
    [   22.360000] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
    [   30.082281] i2c /dev entries driver
    [  522.580554] asoc-simple-card soc:sound: asoc_simple_card_dai_link_of: Can't find simple-audio-card,cpu DT node
    [  522.580575] asoc-simple-card soc:sound: parse error -22
    [  522.580612] asoc-simple-card: probe of soc:sound failed with error -22
```
</details>

<details>
    <summary>cat /var/log/seeed-voicecard.log</summary>

```
    + dtparam i2c_arm=on
    + modprobe i2c-dev
    + dtparam spi=on
    + _VER_RUN=
    + CONFIG=/boot/config.txt
    ++ i2cdetect -y 1 0x1a 0x1a
    ++ egrep '(1a|UU)'
    ++ awk '{print $2}'
    + is_1a=1a
    ++ i2cdetect -y 1 0x35 0x35
    ++ egrep '(35|UU)'
    ++ awk '{print $2}'
    + is_35=
    ++ i2cdetect -y 1 0x3b 0x3b
    ++ awk '{print $2}'
    ++ egrep '(3b|UU)'
    + is_3b=
    + RPI_HATS='seeed-2mic-voicecard seeed-4mic-voicecard seeed-8mic-voicecard'
    + overlay=
    + '[' x1a '!=' x ']'
    + '[' x == x ']'
    + echo 'install 2mic'
    install 2mic
    + overlay=seeed-2mic-voicecard
    + asound_conf=/etc/voicecard/asound_2mic.conf
    + asound_state=/etc/voicecard/wm8960_asound.state
    + '[' x '!=' x ']'
    + '[' x '!=' x ']'
    + '[' seeed-2mic-voicecard ']'
    + echo Install seeed-2mic-voicecard ...
    Install seeed-2mic-voicecard ...
    + rm /etc/asound.conf
    rm: cannot remove '/etc/asound.conf': No such file or directory
    + rm /var/lib/alsa/asound.state
    ++ get_kernel_version
    ++ local ZIMAGE IMG_OFFSET
    ++ _VER_RUN=
    ++ '[' -z '' ']'
    ++ ZIMAGE=/boot/kernel.img
    +++ LC_ALL=C
    +++ grep -abo $'\037\213\b' /boot/kernel.img
    +++ head -n 1
    +++ cut -d : -f 1
    ++ IMG_OFFSET=18092
    +++ dd if=/boot/kernel.img obs=64K ibs=4 skip=4523
    +++ zcat
    +++ grep -a -m1 'Linux version'
    +++ awk '{ print $3; }'
    +++ strings

    gzip: stdout: Broken pipe
    dd: writing to 'standard output': Broken pipe
    933888+0 records in
    56+0 records out
    3670016 bytes (3.7 MB, 3.5 MiB) copied, 3.46432 s, 1.1 MB/s
    ++ _VER_RUN=4.19.42+
    ++ echo 4.19.42+
    ++ return 0
    + kernel_ver=4.19.42+
    + [[ 4.19.42+ =~ ^4\.19.*$ ]]
    + for i in $RPI_HATS
    + '[' seeed-2mic-voicecard == seeed-2mic-voicecard ']'
    + do_overlay seeed-2mic-voicecard 0
    + ov=seeed-2mic-voicecard
    + RET=0
    + DEFAULT=--defaultno
    + CURRENT=0
    ++ get_overlay seeed-2mic-voicecard
    ++ ov=seeed-2mic-voicecard
    ++ grep -q -E '^dtoverlay=seeed-2mic-voicecard' /boot/config.txt
    ++ echo 1
    + '[' 1 -eq 0 ']'
    + '[' 0 -eq 0 ']'
    + ASK_TO_REBOOT=1
    + '[' 0 -eq 0 ']'
    + sed /boot/config.txt -i -e 's/^#dtoverlay=seeed-2mic-voicecard/dtoverlay=seeed-2mic-voicecard/'
    + grep -q -E '^dtoverlay=seeed-2mic-voicecard' /boot/config.txt
    + printf 'dtoverlay=seeed-2mic-voicecard\n'
    + STATUS=enabled
    + for i in $RPI_HATS
    + '[' seeed-4mic-voicecard == seeed-2mic-voicecard ']'
    + echo Uninstall seeed-4mic-voicecard ...
    Uninstall seeed-4mic-voicecard ...
    + do_overlay seeed-4mic-voicecard 1
    + ov=seeed-4mic-voicecard
    + RET=1
    + DEFAULT=--defaultno
    + CURRENT=0
    ++ get_overlay seeed-4mic-voicecard
    ++ ov=seeed-4mic-voicecard
    ++ grep -q -E '^dtoverlay=seeed-4mic-voicecard' /boot/config.txt
    ++ echo 1
    + '[' 1 -eq 0 ']'
    + '[' 1 -eq 0 ']'
    + '[' 1 -eq 0 ']'
    + '[' 1 -eq 1 ']'
    + sed /boot/config.txt -i -e 's/^dtoverlay=seeed-4mic-voicecard/#dtoverlay=seeed-4mic-voicecard/'
    + STATUS=disabled
    + for i in $RPI_HATS
    + '[' seeed-8mic-voicecard == seeed-2mic-voicecard ']'
    + echo Uninstall seeed-8mic-voicecard ...
    Uninstall seeed-8mic-voicecard ...
    + do_overlay seeed-8mic-voicecard 1
    + ov=seeed-8mic-voicecard
    + RET=1
    + DEFAULT=--defaultno
    + CURRENT=0
    ++ get_overlay seeed-8mic-voicecard
    ++ ov=seeed-8mic-voicecard
    ++ grep -q -E '^dtoverlay=seeed-8mic-voicecard' /boot/config.txt
    ++ echo 1
    + '[' 1 -eq 0 ']'
    + '[' 1 -eq 0 ']'
    + '[' 1 -eq 0 ']'
    + '[' 1 -eq 1 ']'
    + sed /boot/config.txt -i -e 's/^dtoverlay=seeed-8mic-voicecard/#dtoverlay=seeed-8mic-voicecard/'
    + STATUS=disabled
    + echo 'create seeed-2mic-voicecard asound configure file'
    create seeed-2mic-voicecard asound configure file
    + ln -s /etc/voicecard/asound_2mic.conf /etc/asound.conf
    + echo 'create seeed-2mic-voicecard asound status file'
    create seeed-2mic-voicecard asound status file
    + ln -s /etc/voicecard/wm8960_asound.state /var/lib/alsa/asound.state
    + alsactl restore
    Found hardware: "bcm2835_alsa" "Broadcom Mixer" "" "" ""
    Hardware is initialized using a generic method
    alsactl: set_control:1325: failed to obtain info for control #6 (No such file or directory)
    + amixer cset numid=3 1
    numid=3,iface=MIXER,name='PCM Playback Route'
    ; type=INTEGER,access=rw------,values=1,min=0,max=2,step=0
    : values=1
```
</details>

**Comment by turmary** [comment]
hi @martinjuhasz 
Nothing need to do except reboot.

Below commands
```
sudo dtoverlay i2s-mmap
sudo dtoverlay seeed-2mic-voicecard
```
not functional.

dtbo is configed by /boot/config.txt and load by kernel while not above commands.

**Comment by cydia2020** [comment]
Same issue here. seeed-voicecard.service is not able to start, cannot find i2s-mmap when trying to dtoverlay it.

**Comment by turmary** [comment]
https://github.com/raspberrypi/linux/issues/2995#issue-451152007

**Comment by turmary** [comment]
#https://github.com/raspberrypi/linux/issues/2995#issue-451152007

**Comment by turmary** [comment]
#https://github.com/raspberrypi/linux/issues/2995

**Comment by turmary** [comment]
@cydia2020 we don't need dtoverlay command in kernel version 4.19.x.

**Comment by pelwell** [comment]
The i2s-mmap overlay has gone because the "mmap" mode is enabled by default since the 4.7 kernel.

**Comment by martinjuhasz** [comment]
this seems to fail for everyone with the latest raspbian image, trying to install seeed-voicecard. i'm using a raspberry pi zero w.

@cydia2020 @wdavalil @norbusan on which device do you get this problem?

**Comment by norbusan** [comment]
RPi 3b+, latest raspbian image

**Comment by cydia2020** [comment]
RPi 3B+, latest raspbian

**Comment by cyberius0** [comment]
RPi3+, did apt upgrade, respeaker is not listed in arecord -L
I really thought it is damaged till I found this open issue. Did anybody solve this?

**Comment by DigitalElise** [comment]
Same here, RPi 3B+, latest raspbian.

Raspbian Buster Lite
Minimal image based on Debian Buster
Version:June 2019
Release date:2019-06-20
Kernel version:4.19

**Comment by norbusan** [comment]
@DigitalElise Hmm, isn't that already the buster based Raspbian? There the compilation of the reseed card doesn't work, at least in my case, since the `fixdep` utility in the raspberrypi-kernel-headers:armhf packages is a x86_64 binary ...

**Comment by thangnd85** [comment]
Same here, Raspbian Buster
Kernel 4.19.50
Trying to revert to 4.19.42 
`wget http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel_1.20190517-1_armhf.deb
sudo dpkg -i raspberrypi-kernel_1.20190517-1_armhf.deb
cd ~
wget http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel-headers_1.20190517-1_armhf.deb
sudo dpkg -i raspberrypi-kernel-headers_1.20190517-1_armhf.deb
sudo apt-mark hold raspberrypi-kernel raspberrypi-kernel-headers`
Ofcourse, it work. But hope that we can find a better solution

**Comment by Pillar1989** [comment]
@thangnd85 You are right. We will solve it soon.

**Comment by norbusan** [comment]
The bug with fixdep I reported to raspbian and it was fixed over night, see https://github.com/raspberrypi/firmware/issues/1155

**Comment by Pillar1989** [comment]
@norbusan Thank you so much for providing such important information. It seems that the problem is not on our side. All we can do is wait.

**Comment by norbusan** [comment]
@Pillar1989 I can confirm that with the latest state of the Raspbian mirrors I can compile, install, and after reboot the card is properly initialized.

Thanks a lot. I think we can close this issue.

**Comment by martinjuhasz** [comment]
cool! Thanks to all for keeping an eye on this and providing information.

**Comment by bachoo786** [comment]
I am still facing the same issue as described in the original OP. Do we have a solution yet? Thanks
